service: tick-tack
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  memorySize: 128
  timeout: 10

functions:
  tick-tack:
    name: tick-tack
    handler: index.run
    events:
      - schedule: 
          rate: cron(0/1 * * * ? *)
          enabled: true
      - eventBridge:
          enabled: true
          name: fire-every-minute
          description: "Fire every minute"
          schedule: cron(0/1 * * * ? *)
        